version: '3.7'

services:  
  web:
    restart: always
    build:
      context: ./SOFTWARE_TESIS/ARSAC/Backend/ARSAC/
      dockerfile: Dockerfile.prod
    command: gunicorn SISTEMA_ARSAC.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./SOFTWARE_TESIS/ARSAC/Backend/ARSAC/static:/home/app/web/static
      - ./SOFTWARE_TESIS/ARSAC/Backend/ARSAC/media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./SOFTWARE_TESIS/envs/Arsac/.env.prod
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./SOFTWARE_TESIS/ARSAC/Backend/ARSAC/static:/home/app/web/static
      - ./SOFTWARE_TESIS/ARSAC/Backend/ARSAC/media:/home/app/web/media
      #- /etc/ssl/certs/propios/unicesmag:/certs
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media: